Update build requirements and options for Mixxx 2.1.0
rpmfusion/mixxx pull request #1
Opened 2018-03-11 14:21 UTC by uklotzde

As promised I've collected a set of changes to support the distribution of the upcoming version 2.1.0. All modifications separated into individual commits for easy review and assessment.

I was able to build and install RPMs for fc27.x86_64 locally without any issues using the default python2-scons 3.0.1.

@Be-ing As a Fedora user you might have a look at this, too?

2018-03-11 14:29 UTC, Be-ing commented on mixxx.spec
> +#rm -rf lib/vamp lib/libebur128 lib/soundtouch-2.0.0 lib/xwax lib/gmock-1.7.0 lib/gtest-1.7.0
Should we remove the version numbers from the directories upstream?

2018-03-11 14:44 UTC, uklotzde commented on mixxx.spec
> +#rm -rf lib/vamp lib/libebur128 lib/soundtouch-2.0.0 lib/xwax lib/gmock-1.7.0 lib/gtest-1.7.0
I've started the renaming of subdirectories when updating Vamp and just recently for libebur128 (pending PR). At that time I was not aware of code like this and still unsure if it was the right decision.

The version numbers in the directory names are handy at first sight, but they are redundant and cause unnecessary changes with every version upgrade and will break external code like this. I would prefer to drop them step by step. What do you think?

2018-03-11 17:26 UTC, kwizart requested changes
This looks very nice update.
Please create a separate issue on our bugzilla.rpmfusion.org to get this PR merged.
Also would you consider to maintain this package in RPM Fusion directly ?
https://rpmfusion.org/Contributors

2018-03-11 17:27 UTC, kwizart commented on mixxx.spec
> +BuildRequires:  opus-devel opusfile-devel
Please use one BR by line, this is more readable with SCM tools

2018-03-11 17:27 UTC, kwizart commented on mixxx.spec
> +BuildRequires:  ffmpeg-devel
Try to sort dependencies alphabetically.

2018-03-11 17:28 UTC, kwizart commented on mixxx.spec
> +#rm -rf lib/vamp lib/libebur128 lib/soundtouch-2.0.0 lib/xwax lib/gmock-1.7.0 lib/gtest-1.7.0
Maybe use a wildcard until/if the dependencies are removed/updated upstream.

2018-03-11 22:29 UTC, Be-ing commented on mixxx.spec
> +#rm -rf lib/vamp lib/libebur128 lib/soundtouch-2.0.0 lib/xwax lib/gmock-1.7.0 lib/gtest-1.7.0
I'd prefer to remove the version numbers upstream now that we realize they create issues for downstream packagers.

2018-03-13 05:35 UTC, uklotzde commented
Thanks for your reply, @kwizart. I did only hold back the reordering of the build dependencies in the initial commits, because I wanted to limit the change set ;)

I will open a request on bugzilla as suggested. Considering the fact that at least 2 developers in our team are using Fedora as their main OS taking care of this package is indeed an option.

2018-03-13 05:47 UTC, uklotzde commented
https://bugzilla.rpmfusion.org/show_bug.cgi?id=4826

2018-10-15 05:05 UTC, sergiomb2 commented
as bug https://bugzilla.rpmfusion.org/show_bug.cgi?id=4826 resolved as fixed

2018-10-15 05:05 UTC, closed without merging